### ISSUE TITLE
Criar as estórias

### ISSUE THREAD

**Issue by RegisMelgaco** [Red-Ovenbirds/taipa-builder#1]
Escrever quais utilidades serão desenvolvidas neste framework, em formato de estória.

**Comment by RegisMelgaco** [comment]
Acho que são as seguintes funcionalidades:

Através de um JSON com marcações especiais do nosso packege é possível criar um Widget com vários dos elementos abaixo um acima do outro em ordem.

1. Texto Simples
  1.1 corpo
  1.2 título
2. Imagem
  2.1 Via url
  2.2 Com bitmap
  2.3 Via path local
3. Checkbox
  3.1 Listener ao ser selecionado com o estado
  3.2 Salvar localmente ao chamar função
  3.3 Salvar localemente sempre que atualizar o estado
4. Video
  4.1 Via url
  4.2 Via path local

**Comment by Jagni** [comment]
Acho que a funcionalidade 3 não entra no nosso escopo

**Comment by Jagni** [comment]
Sugestão: elemento "Custom Widget" que exibe um widget definido externamente

**Comment by RegisMelgaco** [comment]
> Acho que a funcionalidade 3 não entra no nosso escopo

True

**Comment by RegisMelgaco** [comment]
> Sugestão: elemento "Custom Widget" que exibe um widget definido externamente

Que tal ser o widget base que a pessoa faz a herança, aí adiciona essa classe ao builder. Talvez adicionar criando um CustomBuilder ou só adicionar as propriedades mesmo (minha preferencia).

**Comment by alysonNBS** [comment]
> Acho que a funcionalidade 3 não entra no nosso escopo

Concordo

> Sugestão: elemento "Custom Widget" que exibe um widget definido externamente

Achei interessante. Pra incrementar mais (fora do nosso MVP), podemos adicionar Widget que a gente ache interessante ser usado em alguma outra aplicação (como esse checkbox, por exemplo).

**Comment by alysonNBS** [comment]
> > Sugestão: elemento "Custom Widget" que exibe um widget definido externamente
> 
> Que tal ser o widget base que a pessoa faz a herança, aí adiciona essa classe ao builder. Talvez adicionar criando um CustomBuilder ou só adicionar as propriedades mesmo (minha preferencia).

Não entendi muito bem qual a vantagem de fazermos um Widget base para ser realizado herança se a ideia é justamente que o usuário do taipar possa adicionar um Widget qualquer.

**Comment by RegisMelgaco** [comment]
> > Acho que a funcionalidade 3 não entra no nosso escopo
> 
> Concordo
> 
> > Sugestão: elemento "Custom Widget" que exibe um widget definido externamente
> 
> Achei interessante. Pra incrementar mais (fora do nosso MVP), podemos adicionar Widget que a gente ache interessante ser usado em alguma outra aplicação (como esse checkbox, por exemplo).

Dependendo de como a gente decidir arquitetar entra sim no MVP. Talvez a gente só tenha certeza com um esboço de como iremos fazer.

**Comment by RegisMelgaco** [comment]
> > > Sugestão: elemento "Custom Widget" que exibe um widget definido externamente
> > 
> > 
> > Que tal ser o widget base que a pessoa faz a herança, aí adiciona essa classe ao builder. Talvez adicionar criando um CustomBuilder ou só adicionar as propriedades mesmo (minha preferencia).
> 
> Não entendi muito bem qual a vantagem de fazermos um Widget base para ser realizado herança se a ideia é justamente que o usuário do taipar possa adicionar um Widget qualquer.

A gente cria um widget base que enforçar as características que nós precisamos para o builder constrir, o que exatamente depende da implementação. Pensei em coisas tipo, um propriedade que é a marcação que haverá no JSON que indica que será usado tal componete, exemplo:

Marcação: txt
JSON: {"txt": "Varias coisas escritas no exemplo de um JSON com texto"}
Componente:
```dart
class TextBrick extends  BaseBrick {
  TextBrick() {
    mark = 'txt';
  }
}
```

**Comment by Jagni** [comment]
@alysonNBS É bem comum packages oferecem dessa forma. 

Mas normalmente Interfaces/Protocolos, pra que sua classe implemente ao inves de uma Classe pra herdar.

É uma estrategia válida, mas acho que a gente devia dar uma olhada em quais outras alguns pacotes em Dart adotam. Se não me engano daria pra usar Generic Typing pra passar uma Classe como parametro e criar uma instancia somente no nosso builder interno, por exemplo.

Em resumo bó estudar

**Comment by Jagni** [comment]
@RegisMelgaco Lá no nosso builder como a gente faria essa busca de qual classe possui tal mark?

Pra essa parte da notação uma forma que eu tava imaginando seria termos um Parser, funcionaria de forma mais "engessada" mesmo. Mas isso deixaria bem separada a parte de notacao e os widgets, o que acho ser vantajoso. Isso porque se o usuário quiser ele só instancia os widgets diretamente num container dele, seria útil pra montar telas "estáticas".

Os Widgets focariam somente em receber parametros e exibir interface.

O Parser leria um nó e retornaria uma instancia de algum dos nossos Widgets. A classe do Widget ele escolhe de acordo com o que tem no nó. Seria de acordo com a string passada num parametro "mark" por exemplo.

Um Builder nosso receberia um JSON e iria fazer chamadas ao Parser para cada um dos nós.

O Builder popularia o parametro children de um Container nosso.

**Comment by RegisMelgaco** [comment]
@Jagni, tu tem alguma recomendação de leitura? Acho que pra mim e pro @alysonNBS tá faltando literatura, num sei.

**Comment by RegisMelgaco** [comment]
Eu tô dando uma buscada nesse livro as arquiteturas que a gente pode adotar: 
[Design Patterns - Elements of Reusable Object-Oriented Software](https://github.com/Red-Ovenbirds/taipa-builder/files/3657919/Design.Patterns.-.Elements.of.Reusable.Object-Oriented.Software.zip)

Acho que é um caminho interessante dar uma buscada aqui uma mistura desses padrões para resolver bem o problema.

**Comment by RegisMelgaco** [comment]
> @RegisMelgaco Lá no nosso builder como a gente faria essa busca de qual classe possui tal mark?
> 
> Pra essa parte da notação uma forma que eu tava imaginando seria termos um Parser, funcionaria de forma mais "engessada" mesmo. Mas isso deixaria bem separada a parte de notacao e os widgets, o que acho ser vantajoso. Isso porque se o usuário quiser ele só instancia os widgets diretamente num container dele, seria útil pra montar telas "estáticas".
> 
> Os Widgets focariam somente em receber parametros e exibir interface.
> 
> O Parser leria um nó e retornaria uma instancia de algum dos nossos Widgets. A classe do Widget ele escolhe de acordo com o que tem no nó. Seria de acordo com a string passada num parametro "mark" por exemplo.
> 
> Um Builder nosso receberia um JSON e iria fazer chamadas ao Parser para cada um dos nós.
> 
> O Builder popularia o parametro children de um Container nosso.

O que tu quer fazer é algo com uns elementos desses?

"Peças de construção": os widgets que vão receber os dados e iram compor o layout.
Leitor: que vai fazer o tratamento do input (talvez um JSON) e gerará as chamadas do construtor com os dados para dada peça
Construtor: que vai Construir o elemento que será exibido na tela usando as peças e aplincando os estilos, dados e afins

**Comment by Jagni** [comment]
@RegisMelgaco Exatamente! No fim das contas o que importa pro Builder é: receber instâncias dos building blocks. 

Composite se aplicaria muito bem nos Building Blocks.

O Parser poderia usar Visitor pra percorrer o JSON de forma padronizada. Ele poderia fazer chamadas pra uma Factory pra instanciar cada um dos Building Blocks.

Eu tava até vendo algumas palestras aqui que abordam isso. Quando eu tiver tempo vou sentar e organizar o emaranhado de anotacoes que eu fiz.

Pra ficar mais facil da gente entender e estruturar o projeto em si podemos fazer a parte da notação só depois de já ter os building blocks. Teríamos já uma v1 e v2. A notação realmente já é um plus, só uma alternativa pros devs poderem "montar" a interface de um jeito mais pratico.

Quando eu chegar é bom montarmos juntos um diagrama da arquitetura pra cada uma das versoes, fica bem mais facil de entender.

**Comment by Jagni** [comment]
@RegisMelgaco Meu primeiro contato foi o do Erich Gamma. Acho que é o que todo mundo usa.

Mas pelo que eu me lembro ele é basicamente só um catálogo. Vi a imagem que vc mandou no zipzop e acho que ela é ponto de partida até melhor.

Voces podem ir pesquisando sobre alguns que tem naquela imagem mesmo e pensar nas relacoes entre eles, quando a gente se reunir discute quais se aplicam melhor.

(só quero chegar logo ;-; kkkk)

**Comment by RegisMelgaco** [comment]
Estorias oficiais

1. Texto Simples
  1.1 corpo
  1.2 título
2. Imagem
  2.1 Via url
  2.2 Com bitmap
  2.3 Via path local
3. Video
  3.1 Via url
  3.2 Via path local
4. Audio
5. Arquivo

6. Estilização
  6.1 Poder estilizar componentes especificos
  6.2 Poder definir estilo por tipo de componente
  6.3 Poder estilizar o container de componentes

*7. CustomWidget: Decrarar novos widgets reutilizáveis que herdam de BaseWidget
8. FreeWidget: Um widget que pode colocar qualquer widget dentro
