### ISSUE TITLE
TextClayblock/ref não lida bem com strings muito grandes e sem espaços

### ISSUE THREAD

**Issue by Jagni** [Red-Ovenbirds/taipa-builder#29]
![image](https://drive.google.com/uc?export=view&id=1XHeW7vo3YeOH1lAqI8i8QN54MhttEhwD)

Como não cabe numa só linha o comportamento do Text coloca o texto em uma nova linha. Além disso textos muito grandes que possuem espaços ficam alinhados à esquerda com o demarcador.

# Sugestões
### Usar 2 Texts
Ao invés de adicionar o caractere na própria string usar a seguinte estrutura:

```dart
Row
(mainAxisAlignment: MainAxisAlignment.start,
 crossAxisAlignment: CrossAxisAlignment.start,
  children:
   [
    SizedBox(
     width: Theme.of(context).textTheme.body1.fontSize,
     child: Text("•", textAlign: TextAlign.center)
    ),
    Expanded(
     child: Text(content)
    ),
   ]
)
```
Isso faz com que o texto do conteúdo fique "identado" e garante que o demarcador sempre fique no canto esquerdo de cima.

![image](https://drive.google.com/uc?export=view&id=1LPSUpQItLG51Y-cZGbcxxAbqvehmFSHj)

### Permitir customizar o demarcador
Uma string poderia ser passada como parametro ao clayblock: •, -, *, >

### Renomear
Acho que é mais genérico e caracteriza melhor item, itemize, list... etc. ao invés de ref.

**Comment by RegisMelgaco** [comment]
> ### Renomear
> Acho que é mais genérico e caracteriza melhor item, itemize, list... etc. ao invés de ref.

Concordo. Acho que fica bom mudar pra "ul-item" de "unordered list item", algo parecido com ul do HTML.

**Comment by RegisMelgaco** [comment]
> ### Permitir customizar o demarcador
> Uma string poderia ser passada como parametro ao clayblock: •, -, *, >

Acho importante ter essa estilização. Mas fazer dessa forma deixaria essa estilização assimétrica das outras, como mudar o tamanho da fonte, que faz parte de estilização..

**Comment by Jagni** [comment]
> > ### Permitir customizar o demarcador
> > Uma string poderia ser passada como parametro ao clayblock: •, -, *, >
> 
> Acho importante ter essa estilização. Mas fazer dessa forma deixaria essa estilização assimétrica das outras, como mudar o tamanho da fonte, que faz parte de estilização..

Acho que não tem relação, essa string seria conteúdo. Aumentar o tamanho, padding ou cor dessa string é que ficaria em Style mesmo.

Poderia ser um _optional named parameter_ em DataClayblock. O nome poderia ser _typeParameter_ do tipo dynamic. Cada clayblock trataria seus typeParameters, usando um valor default caso ele seja inválido.
