### ISSUE TITLE
Diagrama de Componentes

### ISSUE THREAD

**Issue by Jagni** [Red-Ovenbirds/taipa-builder#4]
![image](https://drive.google.com/uc?export=view&id=1iN1qhkCDFEEru2lKdgDVlf44a_O6nOxo)

Diagrama criado no [Visual Paradigm Online](https://online.visual-paradigm.com/pt/)
https://drive.google.com/file/d/1xsOJbz_lR5TlCUT0qBF59CsDWbP_cXrW/view?usp=sharing

Thread para discussões e sugestões da proposta atual.

**Comment by RegisMelgaco** [comment]
Ei mah, tá faltando os "Styling" que a gente tinha conversado ontem na sala do Cidcley.

**Comment by alysonNBS** [comment]
Achei top.

**Comment by alysonNBS** [comment]
> Ei mah, tá faltando os "Styling" que a gente tinha conversado ontem na sala do Cidcley.

Mr. Regis estava me falando que deveria ter Styling para o Clayblock Factory e também para o Clay Instantiation.

Me parece estranho ter em Clay Instantiation porque eu entendi que os objetos já estariam instanciados, logo, já teriam seus devidos Styling definidos ou seriam definidos em Container.

**Comment by Jagni** [comment]
> Ei mah, tá faltando os "Styling" que a gente tinha conversado ontem na sala do Cidcley.

Pra deixar registrado: 
Seria o Theme, Individual e o do container né?

O Individual se sobrepõe ao Theme. 

Acho que o Theme poderia ser um singleton.

Os construtores dos Clayblocks usariam sempre os atributos que estiverem definidos lá por padrão. Depois verificam se algum styling individual foi passado como parametro e os aplicam.

**Comment by Jagni** [comment]
Vocês conseguem editar o diagrama?

**Comment by Jagni** [comment]
> > Ei mah, tá faltando os "Styling" que a gente tinha conversado ontem na sala do Cidcley.
> 
> Mr. Regis estava me falando que deveria ter Styling para o Clayblock Factory e também para o Clay Instantiation.
> 
> Me parece estranho ter em Clay Instantiation porque eu entendi que os objetos já estariam instanciados, logo, já teriam seus devidos Styling definidos ou seriam definidos em Container.

É que eles seriam instanciados pelos devs, a ideia é que eles possam passar como parâmetro/setar alguma propriedade. Pra isso eles teriam q usar as classes de styling que a gente definir.

**Comment by RegisMelgaco** [comment]
# Como Régis está pensando
Eu acredito que nosso diagrama está incompleto, uma vez que não se faz claro como estilizar as seguintes estruturas:
- Um tipo de Clay. Ex: Todos os títulos de um container.
- Uma instância Clay. Ex: O segundo bloco de texto no meu container.
- O próprio container (Não fica claro onde se é nesse ponto representado no diagrama).

**Comment by Jagni** [comment]
> # Como Régis está pensando
> Eu acredito que nosso diagrama está incompleto, uma vez que não se faz claro como estilizar as seguintes estruturas:
> 
> * Um tipo de Clay. Ex: Todos os títulos de um container.
> * Uma instância Clay. Ex: O segundo bloco de texto no meu container.
> * O próprio container (Não fica claro onde se é nesse ponto representado no diagrama).

É como eu to falando msm n? ._. 

* Theme
* Individual
* Container

Tava querendo confirmar pra ai sim incluir no diagrama

**Comment by RegisMelgaco** [comment]
> > # Como Régis está pensando
> > Eu acredito que nosso diagrama está incompleto, uma vez que não se faz claro como estilizar as seguintes estruturas:
> > 
> > * Um tipo de Clay. Ex: Todos os títulos de um container.
> > * Uma instância Clay. Ex: O segundo bloco de texto no meu container.
> > * O próprio container (Não fica claro onde se é nesse ponto representado no diagrama).
> 
> É como eu to falando msm n? ._.
> 
> * Theme
> * Individual
> * Container
> 
> Tava querendo confirmar pra ai sim incluir no diagrama

Atá. Pois é isso mesmo.

**Comment by Jagni** [comment]
Confirmem aqui se tá tudo top e posso fechar a issue #22 
@alysonNBS @RegisMelgaco @Joe02 @CrisCoutinho

**Comment by alysonNBS** [comment]
> Vocês conseguem editar o diagrama?

Não

**Comment by alysonNBS** [comment]
> Confirmem aqui se tá tudo top e posso fechar a issue #22
> @alysonNBS @RegisMelgaco @Joe02 @CrisCoutinho

Precisa explicitar o que o Notation enviar para o Builder. No caso:
- Widgets
- Individual Style (Optional)

**Comment by Jagni** [comment]
Notas sobre Notation incluídas!
